name = "FluxTools"
uuid = "120c222c-08b0-46af-b528-1753ed684f8f"
authors = ["piever <pietro.vertechi@protonmail.com> and contributors"]
version = "0.1.0"

[deps]
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"

[compat]
Functors = "0.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
